platform :ios, '8.0'
use_frameworks!
target 'ZWNetUtilsDemo' do
pod 'IQKeyboardManager', '~> 4.0.0'
pod 'AFNetworking', '~> 2.0'
pod 'MBProgressHUD', '~> 0.9.2'
pod 'MJRefresh', '~> 3.1.0'
pod 'SDWebImage', '~> 3.7.5'
#弹出视图
pod 'WYPopoverController', '~> 0.2.2'
end
